version: '3.8'

services:
  web:
    build: .
    container_name: flask_marketplace
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=sqlite:////app/instance/market.db
    volumes:
      - ./instance:/app/instance
    networks:
      - flask_network
    # Use gunicorn for production
    command: gunicorn --bind 0.0.0.0:5000 run:app

networks:
  flask_network:
    driver: bridge